
help: ## Show this Makefile's help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

prepare: ## Prepare Terraform's environment by downloading and initializing its plugins and backends
	@terraform init

validate: prepare ## Run a static validation of the local files
	@terraform validate
	@tfsec --exclude-downloaded-modules

clean: ## Remove any temporary artefacts generated by this Makefile
	@rm -rf $(CURDIR)/.terraform

.PHONY: clean validate prepare help
