
# Disable CGO to avoid error "cgo: exec /missing-cc: fork/exec /missing-cc: no such file or directory"
# Ref. https://golang.org/cmd/cgo/
export CGO_ENABLED=0

BACKEND_CONFIG_FILE ?= ./backend-config

help: ## Show this Makefile's help
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

prepare: ## Prepare Terraform's environment by downloading and initializing its plugins and backends
	make -C $(CURDIR) .terraform/plugins/selections.json

validate: .terraform/plugins/selections.json ## Run a static validation on the local files
	@terraform validate
	@tfsec --exclude-downloaded-modules
	@go fmt ./tests/
	@golangci-lint run ./tests/

tests: ## Execute the test harness
	@go test -v -timeout 30m ./tests/

plan: .terraform/plugins/selections.json ## Deploy (apply) the terraform changes to production
	@terraform plan -compact-warnings -detailed-exitcode -lock=false

deploy: .terraform/plugins/selections.json ## Deploy (apply) the terraform changes to production
	@terraform apply -auto-approve

clean: ## Remove any temporary artefacts generated by this Makefile
	@rm -rf $(CURDIR)/.terraform

.PHONY: clean validate prepare help tests plan deploy

.terraform/plugins/selections.json:
	@terraform init -backend-config=$(BACKEND_CONFIG_FILE)
